-- Convocatorias Mundial 2026 (de worldcup.squads.json) — alimenta el mercado Goleador
insert into team_squads (team, player, pos) values
  ('Czech Republic','Matěj Kovář','GK'),
  ('Czech Republic','David Zima','DF'),
  ('Czech Republic','Tomáš Holeš','DF'),
  ('Czech Republic','Robin Hranáč','DF'),
  ('Czech Republic','Vladimír Coufal','DF'),
  ('Czech Republic','Štěpán Chaloupek','DF'),
  ('Czech Republic','Ladislav Krejčí','DF'),
  ('Czech Republic','Vladimír Darida','MF'),
  ('Czech Republic','Adam Hložek','FW'),
  ('Czech Republic','Patrik Schick','FW'),
  ('Czech Republic','Jan Kuchta','FW'),
  ('Czech Republic','Lukáš Červ','MF'),
  ('Czech Republic','Mojmír Chytil','FW'),
  ('Czech Republic','David Jurásek','DF'),
  ('Czech Republic','Pavel Šulc','FW'),
  ('Czech Republic','Jindřich Staněk','GK'),
  ('Czech Republic','Lukáš Provod','MF'),
  ('Czech Republic','Michal Sadílek','MF'),
  ('Czech Republic','Tomáš Chorý','FW'),
  ('Czech Republic','Jaroslav Zelený','DF'),
  ('Czech Republic','David Douděra','DF'),
  ('Czech Republic','Tomáš Souček','MF'),
  ('Czech Republic','Lukáš Horníček','GK'),
  ('Czech Republic','Alexandr Sojka','MF'),
  ('Czech Republic','Hugo Sochůrek','MF'),
  ('Czech Republic','Denis Višinský','FW'),
  ('Mexico','Raúl Rangel','GK'),
  ('Mexico','Jorge Sánchez','DF'),
  ('Mexico','César Montes','DF'),
  ('Mexico','Edson Álvarez','DF'),
  ('Mexico','Johan Vásquez','DF'),
  ('Mexico','Érik Lira','MF'),
  ('Mexico','Luis Romo','MF'),
  ('Mexico','Álvaro Fidalgo','MF'),
  ('Mexico','Raúl Jiménez','FW'),
  ('Mexico','Alexis Vega','FW'),
  ('Mexico','Santiago Giménez','FW'),
  ('Mexico','Carlos Acevedo','GK'),
  ('Mexico','Guillermo Ochoa','GK'),
  ('Mexico','Armando González','FW'),
  ('Mexico','Israel Reyes','DF'),
  ('Mexico','Julián Quiñones','FW'),
  ('Mexico','Orbelín Pineda','MF'),
  ('Mexico','Obed Vargas','MF'),
  ('Mexico','Gilberto Mora','MF'),
  ('Mexico','Mateo Chávez','DF'),
  ('Mexico','César Huerta','FW'),
  ('Mexico','Guillermo Martínez','FW'),
  ('Mexico','Jesús Gallardo','DF'),
  ('Mexico','Luis Chávez','MF'),
  ('Mexico','Roberto Alvarado','FW'),
  ('Mexico','Brian Gutiérrez','MF'),
  ('South Africa','Ronwen Williams','GK'),
  ('South Africa','Thabang Matuludi','DF'),
  ('South Africa','Khulumani Ndamane','DF'),
  ('South Africa','Teboho Mokoena','MF'),
  ('South Africa','Thalente Mbatha','MF'),
  ('South Africa','Aubrey Modiba','DF'),
  ('South Africa','Oswin Appollis','FW'),
  ('South Africa','Tshepang Moremi','FW'),
  ('South Africa','Lyle Foster','FW'),
  ('South Africa','Relebohile Mofokeng','FW'),
  ('South Africa','Themba Zwane','MF'),
  ('South Africa','Thapelo Maseko','FW'),
  ('South Africa','Sphephelo Sithole','MF'),
  ('South Africa','Mbekezeli Mbokazi','DF'),
  ('South Africa','Iqraam Rayners','FW'),
  ('South Africa','Sipho Chaine','GK'),
  ('South Africa','Evidence Makgopa','FW'),
  ('South Africa','Samukele Kabini','DF'),
  ('South Africa','Nkosinathi Sibisi','DF'),
  ('South Africa','Khuliso Mudau','DF'),
  ('South Africa','Ime Okon','DF'),
  ('South Africa','Ricardo Goss','GK'),
  ('South Africa','Jayden Adams','MF'),
  ('South Africa','Olwethu Makhanya','DF'),
  ('South Africa','Kamogelo Sebelebele','FW'),
  ('South Africa','Bradley Cross','DF'),
  ('South Korea','Kim Seung-gyu','GK'),
  ('South Korea','Lee Han-beom','DF'),
  ('South Korea','Lee Gi-hyuk','MF'),
  ('South Korea','Kim Min-jae','DF'),
  ('South Korea','Kim Tae-hyeon','DF'),
  ('South Korea','Hwang In-beom','MF'),
  ('South Korea','Son Heung-min','FW'),
  ('South Korea','Paik Seung-ho','MF'),
  ('South Korea','Cho Gue-sung','FW'),
  ('South Korea','Lee Jae-sung','MF'),
  ('South Korea','Hwang Hee-chan','MF'),
  ('South Korea','Song Bum-keun','GK'),
  ('South Korea','Lee Tae-seok','DF'),
  ('South Korea','Cho Wi-je','DF'),
  ('South Korea','Kim Moon-hwan','DF'),
  ('South Korea','Park Jin-seob','DF'),
  ('South Korea','Bae Jun-ho','MF'),
  ('South Korea','Oh Hyeon-gyu','FW'),
  ('South Korea','Lee Kang-in','MF'),
  ('South Korea','Yang Hyun-jun','MF'),
  ('South Korea','Jo Hyeon-woo','GK'),
  ('South Korea','Seol Young-woo','DF'),
  ('South Korea','Jens Castrop','DF'),
  ('South Korea','Kim Jin-gyu','MF'),
  ('South Korea','Eom Ji-sung','MF'),
  ('South Korea','Lee Dong-gyeong','MF'),
  ('Bosnia and Herzegovina','Nikola Vasilj','GK'),
  ('Bosnia and Herzegovina','Nihad Mujakić','DF'),
  ('Bosnia and Herzegovina','Dennis Hadžikadunić','DF'),
  ('Bosnia and Herzegovina','Tarik Muharemović','DF'),
  ('Bosnia and Herzegovina','Sead Kolašinac','DF'),
  ('Bosnia and Herzegovina','Benjamin Tahirović','MF'),
  ('Bosnia and Herzegovina','Amar Dedić','DF'),
  ('Bosnia and Herzegovina','Armin Gigović','MF'),
  ('Bosnia and Herzegovina','Samed Baždar','FW'),
  ('Bosnia and Herzegovina','Ermedin Demirović','FW'),
  ('Bosnia and Herzegovina','Edin Džeko','FW'),
  ('Bosnia and Herzegovina','Mladen Jurkas','GK'),
  ('Bosnia and Herzegovina','Ivan Bašić','MF'),
  ('Bosnia and Herzegovina','Ivan Šunjić','MF'),
  ('Bosnia and Herzegovina','Amar Memić','MF'),
  ('Bosnia and Herzegovina','Amir Hadžiahmetović','MF'),
  ('Bosnia and Herzegovina','Dženis Burnić','MF'),
  ('Bosnia and Herzegovina','Nikola Katić','DF'),
  ('Bosnia and Herzegovina','Kerim Alajbegović','FW'),
  ('Bosnia and Herzegovina','Esmir Bajraktarević','FW'),
  ('Bosnia and Herzegovina','Stjepan Radeljić','DF'),
  ('Bosnia and Herzegovina','Martin Zlomislić','GK'),
  ('Bosnia and Herzegovina','Haris Tabaković','FW'),
  ('Bosnia and Herzegovina','Nidal Čelik','DF'),
  ('Bosnia and Herzegovina','Jovo Lukić','FW'),
  ('Bosnia and Herzegovina','Ermin Mahmić','MF'),
  ('Canada','Dayne St. Clair','GK'),
  ('Canada','Alistair Johnston','DF'),
  ('Canada','Alfie Jones','DF'),
  ('Canada','Luc de Fougerolles','DF'),
  ('Canada','Joel Waterman','DF'),
  ('Canada','Mathieu Choinière','MF'),
  ('Canada','Stephen Eustáquio','MF'),
  ('Canada','Ismaël Koné','MF'),
  ('Canada','Cyle Larin','FW'),
  ('Canada','Jonathan David','FW'),
  ('Canada','Liam Millar','MF'),
  ('Canada','Tani Oluwaseyi','FW'),
  ('Canada','Derek Cornelius','DF'),
  ('Canada','Jacob Shaffelburg','MF'),
  ('Canada','Moïse Bombito','DF'),
  ('Canada','Maxime Crépeau','GK'),
  ('Canada','Tajon Buchanan','FW'),
  ('Canada','Owen Goodman','GK'),
  ('Canada','Alphonso Davies','DF'),
  ('Canada','Ali Ahmed','FW'),
  ('Canada','Jonathan Osorio','MF'),
  ('Canada','Richie Laryea','DF'),
  ('Canada','Niko Sigur','DF'),
  ('Canada','Promise David','FW'),
  ('Canada','Nathan Saliba','MF'),
  ('Canada','Jayden Nelson','MF'),
  ('Qatar','Mahmud Abunada','GK'),
  ('Qatar','Pedro Miguel','DF'),
  ('Qatar','Lucas Mendes','DF'),
  ('Qatar','Issa Laye','DF'),
  ('Qatar','Jassem Gaber','DF'),
  ('Qatar','Abdulaziz Hatem','MF'),
  ('Qatar','Ahmed Alaaeldin','FW'),
  ('Qatar','Edmilson Junior','FW'),
  ('Qatar','Mohammed Muntari','FW'),
  ('Qatar','Hassan Al-Haydos','FW'),
  ('Qatar','Akram Afif','FW'),
  ('Qatar','Karim Boudiaf','MF'),
  ('Qatar','Ayoub Al-Oui','DF'),
  ('Qatar','Homam Ahmed','DF'),
  ('Qatar','Yusuf Abdurisag','FW'),
  ('Qatar','Boualem Khoukhi','DF'),
  ('Qatar','Ahmed Al-Ganehi','MF'),
  ('Qatar','Sultan Al-Brake','DF'),
  ('Qatar','Almoez Ali','FW'),
  ('Qatar','Ahmed Fathy','MF'),
  ('Qatar','Salah Zakaria','GK'),
  ('Qatar','Meshaal Barsham','GK'),
  ('Qatar','Assim Madibo','MF'),
  ('Qatar','Tahsin Jamshid','FW'),
  ('Qatar','Al-Hashmi Al-Hussain','DF'),
  ('Qatar','Mohamed Manai','FW'),
  ('Switzerland','Gregor Kobel','GK'),
  ('Switzerland','Miro Muheim','DF'),
  ('Switzerland','Silvan Widmer','DF'),
  ('Switzerland','Nico Elvedi','DF'),
  ('Switzerland','Manuel Akanji','DF'),
  ('Switzerland','Denis Zakaria','MF'),
  ('Switzerland','Breel Embolo','FW'),
  ('Switzerland','Remo Freuler','MF'),
  ('Switzerland','Johan Manzambi','MF'),
  ('Switzerland','Granit Xhaka','MF'),
  ('Switzerland','Dan Ndoye','FW'),
  ('Switzerland','Yvon Mvogo','GK'),
  ('Switzerland','Ricardo Rodriguez','DF'),
  ('Switzerland','Ardon Jashari','MF'),
  ('Switzerland','Djibril Sow','MF'),
  ('Switzerland','Christian Fassnacht','FW'),
  ('Switzerland','Rubén Vargas','FW'),
  ('Switzerland','Eray Cömert','DF'),
  ('Switzerland','Noah Okafor','FW'),
  ('Switzerland','Michel Aebischer','MF'),
  ('Switzerland','Marvin Keller','GK'),
  ('Switzerland','Fabian Rieder','MF'),
  ('Switzerland','Zeki Amdouni','FW'),
  ('Switzerland','Aurèle Amenda','DF'),
  ('Switzerland','Luca Jaquez','DF'),
  ('Switzerland','Cedric Itten','FW'),
  ('Brazil','Alisson','GK'),
  ('Brazil','Éderson Silva','MF'),
  ('Brazil','Gabriel Magalhães','DF'),
  ('Brazil','Marquinhos','DF'),
  ('Brazil','Casemiro','MF'),
  ('Brazil','Alex Sandro','DF'),
  ('Brazil','Vinícius Júnior','FW'),
  ('Brazil','Bruno Guimarães','MF'),
  ('Brazil','Matheus Cunha','FW'),
  ('Brazil','Neymar','FW'),
  ('Brazil','Raphinha','FW'),
  ('Brazil','Weverton','GK'),
  ('Brazil','Danilo Luiz','DF'),
  ('Brazil','Bremer','DF'),
  ('Brazil','Léo Pereira','DF'),
  ('Brazil','Douglas Santos','DF'),
  ('Brazil','Fabinho','MF'),
  ('Brazil','Danilo Santos','MF'),
  ('Brazil','Endrick','FW'),
  ('Brazil','Lucas Paquetá','MF'),
  ('Brazil','Luiz Henrique','FW'),
  ('Brazil','Gabriel Martinelli','FW'),
  ('Brazil','Ederson Moraes','GK'),
  ('Brazil','Roger Ibañez','DF'),
  ('Brazil','Igor Thiago','FW'),
  ('Brazil','Rayan','FW'),
  ('Haiti','Johny Placide','GK'),
  ('Haiti','Carlens Arcus','DF'),
  ('Haiti','Keeto Thermoncy','DF'),
  ('Haiti','Ricardo Adé','DF'),
  ('Haiti','Hannes Delcroix','DF'),
  ('Haiti','Carl Sainté','MF'),
  ('Haiti','Derrick Etienne Jr.','FW'),
  ('Haiti','Martin Expérience','DF'),
  ('Haiti','Duckens Nazon','FW'),
  ('Haiti','Jean-Ricner Bellegarde','MF'),
  ('Haiti','Louicius Deedson','FW'),
  ('Haiti','Alexandre Pierre','GK'),
  ('Haiti','Duke Lacroix','DF'),
  ('Haiti','Leverton Pierre','MF'),
  ('Haiti','Ruben Providence','FW'),
  ('Haiti','Lenny Joseph','FW'),
  ('Haiti','Danley Jean Jacques','MF'),
  ('Haiti','Wilson Isidor','FW'),
  ('Haiti','Yassin Fortuné','FW'),
  ('Haiti','Frantzdy Pierrot','FW'),
  ('Haiti','Josué Casimir','FW'),
  ('Haiti','Jean-Kévin Duverne','DF'),
  ('Haiti','Josué Duverger','GK'),
  ('Haiti','Wilguens Paugain','DF'),
  ('Haiti','Dominique Simon','MF'),
  ('Haiti','Woodensky Pierre','MF'),
  ('Morocco','Yassine Bounou','GK'),
  ('Morocco','Achraf Hakimi','DF'),
  ('Morocco','Noussair Mazraoui','DF'),
  ('Morocco','Sofyan Amrabat','MF'),
  ('Morocco','Nayef Aguerd','DF'),
  ('Morocco','Ayyoub Bouaddi','MF'),
  ('Morocco','Chemsdine Talbi','MF'),
  ('Morocco','Azzedine Ounahi','MF'),
  ('Morocco','Soufiane Rahimi','FW'),
  ('Morocco','Brahim Díaz','FW'),
  ('Morocco','Ismael Saibari','MF'),
  ('Morocco','Munir Mohamedi','GK'),
  ('Morocco','Zakaria El Ouahdi','DF'),
  ('Morocco','Issa Diop','DF'),
  ('Morocco','Samir El Mourabet','MF'),
  ('Morocco','Gessime Yassine','MF'),
  ('Morocco','Abde Ezzalzouli','FW'),
  ('Morocco','Chadi Riad','DF'),
  ('Morocco','Youssef Belammari','DF'),
  ('Morocco','Ayoub El Kaabi','FW'),
  ('Morocco','Ayoube Amaimouni','FW'),
  ('Morocco','Ahmed Reda Tagnaouti','GK'),
  ('Morocco','Bilal El Khannouss','MF'),
  ('Morocco','Neil El Aynaoui','MF'),
  ('Morocco','Redouane Halhal','DF'),
  ('Morocco','Anass Salah-Eddine','DF'),
  ('Scotland','Angus Gunn','GK'),
  ('Scotland','Aaron Hickey','DF'),
  ('Scotland','Andy Robertson','DF'),
  ('Scotland','Scott McTominay','MF'),
  ('Scotland','Grant Hanley','DF'),
  ('Scotland','Kieran Tierney','DF'),
  ('Scotland','John McGinn','MF'),
  ('Scotland','Tyler Fletcher','MF'),
  ('Scotland','Lyndon Dykes','FW'),
  ('Scotland','Ché Adams','FW'),
  ('Scotland','Ryan Christie','MF'),
  ('Scotland','Liam Kelly','GK'),
  ('Scotland','Jack Hendry','DF'),
  ('Scotland','Ross Stewart','FW'),
  ('Scotland','John Souttar','DF'),
  ('Scotland','Dominic Hyam','DF'),
  ('Scotland','Ben Gannon-Doak','FW'),
  ('Scotland','George Hirst','FW'),
  ('Scotland','Lewis Ferguson','MF'),
  ('Scotland','Lawrence Shankland','FW'),
  ('Scotland','Craig Gordon','GK'),
  ('Scotland','Nathan Patterson','DF'),
  ('Scotland','Kenny McLean','MF'),
  ('Scotland','Anthony Ralston','DF'),
  ('Scotland','Findlay Curtis','FW'),
  ('Scotland','Scott McKenna','DF'),
  ('Australia','Mathew Ryan','GK'),
  ('Australia','Miloš Degenek','DF'),
  ('Australia','Alessandro Circati','DF'),
  ('Australia','Jacob Italiano','DF'),
  ('Australia','Jordan Bos','DF'),
  ('Australia','Jason Geria','DF'),
  ('Australia','Mathew Leckie','FW'),
  ('Australia','Connor Metcalfe','MF'),
  ('Australia','Mohamed Touré','FW'),
  ('Australia','Ajdin Hrustic','FW'),
  ('Australia','Awer Mabil','FW'),
  ('Australia','Paul Izzo','GK'),
  ('Australia','Aiden O''Neill','MF'),
  ('Australia','Cammy Devlin','MF'),
  ('Australia','Kai Trewin','DF'),
  ('Australia','Aziz Behich','DF'),
  ('Australia','Nestory Irankunda','FW'),
  ('Australia','Patrick Beach','GK'),
  ('Australia','Harry Souttar','DF'),
  ('Australia','Cristian Volpato','FW'),
  ('Australia','Cameron Burgess','DF'),
  ('Australia','Jackson Irvine','MF'),
  ('Australia','Nishan Velupillay','FW'),
  ('Australia','Paul Okon-Engstler','MF'),
  ('Australia','Lucas Herrington','DF'),
  ('Australia','Tete Yengi','FW'),
  ('Paraguay','Gatito Fernández','GK'),
  ('Paraguay','Gustavo Velázquez','DF'),
  ('Paraguay','Omar Alderete','DF'),
  ('Paraguay','Juan José Cáceres','DF'),
  ('Paraguay','Fabián Balbuena','DF'),
  ('Paraguay','Júnior Alonso','DF'),
  ('Paraguay','Ramón Sosa','MF'),
  ('Paraguay','Diego Gómez','MF'),
  ('Paraguay','Antonio Sanabria','FW'),
  ('Paraguay','Miguel Almirón','MF'),
  ('Paraguay','Maurício','MF'),
  ('Paraguay','Orlando Gill','GK'),
  ('Paraguay','José Canale','DF'),
  ('Paraguay','Andrés Cubas','MF'),
  ('Paraguay','Gustavo Gómez','DF'),
  ('Paraguay','Damián Bobadilla','MF'),
  ('Paraguay','Kaku','FW'),
  ('Paraguay','Álex Arce','FW'),
  ('Paraguay','Julio Enciso','FW'),
  ('Paraguay','Braian Ojeda','MF'),
  ('Paraguay','Gabriel Ávalos','FW'),
  ('Paraguay','Gastón Olveira','GK'),
  ('Paraguay','Matías Galarza','MF'),
  ('Paraguay','Gustavo Caballero','MF'),
  ('Paraguay','Isidro Pitta','FW'),
  ('Paraguay','Alexandro Maidana','DF'),
  ('Turkey','Mert Günok','GK'),
  ('Turkey','Zeki Çelik','DF'),
  ('Turkey','Merih Demiral','DF'),
  ('Turkey','Çağlar Söyüncü','DF'),
  ('Turkey','Salih Özcan','MF'),
  ('Turkey','Orkun Kökçü','MF'),
  ('Turkey','Kerem Aktürkoğlu','FW'),
  ('Turkey','Arda Güler','FW'),
  ('Turkey','Deniz Gül','FW'),
  ('Turkey','Hakan Çalhanoğlu','MF'),
  ('Turkey','Kenan Yıldız','FW'),
  ('Turkey','Altay Bayındır','GK'),
  ('Turkey','Eren Elmalı','DF'),
  ('Turkey','Abdülkerim Bardakcı','DF'),
  ('Turkey','Ozan Kabak','DF'),
  ('Turkey','İsmail Yüksek','MF'),
  ('Turkey','İrfan Can Kahveci','FW'),
  ('Turkey','Mert Müldür','DF'),
  ('Turkey','Yunus Akgün','FW'),
  ('Turkey','Ferdi Kadıoğlu','DF'),
  ('Turkey','Barış Alper Yılmaz','FW'),
  ('Turkey','Kaan Ayhan','MF'),
  ('Turkey','Uğurcan Çakır','GK'),
  ('Turkey','Oğuz Aydın','FW'),
  ('Turkey','Samet Akaydin','DF'),
  ('Turkey','Can Uzun','FW'),
  ('United States','Matt Turner','GK'),
  ('United States','Sergiño Dest','DF'),
  ('United States','Chris Richards','DF'),
  ('United States','Tyler Adams','MF'),
  ('United States','Antonee Robinson','DF'),
  ('United States','Auston Trusty','DF'),
  ('United States','Giovanni Reyna','MF'),
  ('United States','Weston McKennie','MF'),
  ('United States','Ricardo Pepi','FW'),
  ('United States','Christian Pulisic','FW'),
  ('United States','Brenden Aaronson','FW'),
  ('United States','Miles Robinson','DF'),
  ('United States','Tim Ream','DF'),
  ('United States','Sebastian Berhalter','MF'),
  ('United States','Cristian Roldan','MF'),
  ('United States','Alex Freeman','DF'),
  ('United States','Malik Tillman','MF'),
  ('United States','Max Arfsten','DF'),
  ('United States','Haji Wright','FW'),
  ('United States','Folarin Balogun','FW'),
  ('United States','Timothy Weah','FW'),
  ('United States','Mark McKenzie','DF'),
  ('United States','Joe Scally','DF'),
  ('United States','Matt Freese','GK'),
  ('United States','Chris Brady','GK'),
  ('United States','Alejandro Zendejas','FW'),
  ('Curaçao','Eloy Room','GK'),
  ('Curaçao','Shurandy Sambo','DF'),
  ('Curaçao','Juriën Gaari','DF'),
  ('Curaçao','Roshon van Eijma','DF'),
  ('Curaçao','Sherel Floranus','DF'),
  ('Curaçao','Godfried Roemeratoe','MF'),
  ('Curaçao','Juninho Bacuna','MF'),
  ('Curaçao','Livano Comenencia','MF'),
  ('Curaçao','Jürgen Locadia','FW'),
  ('Curaçao','Leandro Bacuna','MF'),
  ('Curaçao','Jeremy Antonisse','FW'),
  ('Curaçao','Sontje Hansen','FW'),
  ('Curaçao','Tyrese Noslin','FW'),
  ('Curaçao','Kenji Gorré','FW'),
  ('Curaçao','Ar''jany Martha','MF'),
  ('Curaçao','Jearl Margaritha','FW'),
  ('Curaçao','Brandley Kuwas','FW'),
  ('Curaçao','Armando Obispo','DF'),
  ('Curaçao','Gervane Kastaneer','FW'),
  ('Curaçao','Joshua Brenet','DF'),
  ('Curaçao','Tahith Chong','MF'),
  ('Curaçao','Kevin Felida','MF'),
  ('Curaçao','Riechedly Bazoer','DF'),
  ('Curaçao','Deveron Fonville','DF'),
  ('Curaçao','Tyrick Bodak','GK'),
  ('Curaçao','Trevor Doornbusch','GK'),
  ('Ecuador','Hernán Galíndez','GK'),
  ('Ecuador','Félix Torres','DF'),
  ('Ecuador','Piero Hincapié','DF'),
  ('Ecuador','Joel Ordóñez','DF'),
  ('Ecuador','Jordy Alcívar','MF'),
  ('Ecuador','Willian Pacho','DF'),
  ('Ecuador','Pervis Estupiñán','DF'),
  ('Ecuador','Anthony Valencia','MF'),
  ('Ecuador','John Yeboah','FW'),
  ('Ecuador','Kendry Páez','MF'),
  ('Ecuador','Kevin Rodríguez','FW'),
  ('Ecuador','Moisés Ramírez','GK'),
  ('Ecuador','Enner Valencia','FW'),
  ('Ecuador','Alan Minda','MF'),
  ('Ecuador','Pedro Vite','MF'),
  ('Ecuador','Jordy Caicedo','FW'),
  ('Ecuador','Ángelo Preciado','DF'),
  ('Ecuador','Denil Castillo','MF'),
  ('Ecuador','Gonzalo Plata','FW'),
  ('Ecuador','Nilson Angulo','FW'),
  ('Ecuador','Alan Franco','MF'),
  ('Ecuador','Gonzalo Valle','GK'),
  ('Ecuador','Moisés Caicedo','MF'),
  ('Ecuador','Jeremy Arévalo','FW'),
  ('Ecuador','Jackson Porozo','DF'),
  ('Ecuador','Yaimar Medina','DF'),
  ('Germany','Manuel Neuer','GK'),
  ('Germany','Antonio Rüdiger','DF'),
  ('Germany','Waldemar Anton','DF'),
  ('Germany','Jonathan Tah','DF'),
  ('Germany','Aleksandar Pavlović','MF'),
  ('Germany','Joshua Kimmich','DF'),
  ('Germany','Kai Havertz','FW'),
  ('Germany','Leon Goretzka','MF'),
  ('Germany','Jamie Leweling','MF'),
  ('Germany','Jamal Musiala','MF'),
  ('Germany','Nick Woltemade','FW'),
  ('Germany','Oliver Baumann','GK'),
  ('Germany','Pascal Groß','MF'),
  ('Germany','Maximilian Beier','FW'),
  ('Germany','Nico Schlotterbeck','DF'),
  ('Germany','Angelo Stiller','MF'),
  ('Germany','Florian Wirtz','MF'),
  ('Germany','Nathaniel Brown','DF'),
  ('Germany','Leroy Sané','MF'),
  ('Germany','Nadiem Amiri','MF'),
  ('Germany','Alexander Nübel','GK'),
  ('Germany','David Raum','DF'),
  ('Germany','Felix Nmecha','MF'),
  ('Germany','Malick Thiaw','DF'),
  ('Germany','Assan Ouédraogo','MF'),
  ('Germany','Deniz Undav','FW'),
  ('Ivory Coast','Yahia Fofana','GK'),
  ('Ivory Coast','Ousmane Diomande','DF'),
  ('Ivory Coast','Ghislain Konan','DF'),
  ('Ivory Coast','Jean Michaël Seri','MF'),
  ('Ivory Coast','Wilfried Singo','DF'),
  ('Ivory Coast','Seko Fofana','MF'),
  ('Ivory Coast','Odilon Kossounou','DF'),
  ('Ivory Coast','Franck Kessié','MF'),
  ('Ivory Coast','Ange-Yoan Bonny','FW'),
  ('Ivory Coast','Simon Adingra','FW'),
  ('Ivory Coast','Yan Diomande','FW'),
  ('Ivory Coast','Elye Wahi','FW'),
  ('Ivory Coast','Christopher Opéri','DF'),
  ('Ivory Coast','Oumar Diakité','FW'),
  ('Ivory Coast','Amad Diallo','FW'),
  ('Ivory Coast','Mohamed Koné','GK'),
  ('Ivory Coast','Guéla Doué','DF'),
  ('Ivory Coast','Ibrahim Sangaré','MF'),
  ('Ivory Coast','Nicolas Pépé','FW'),
  ('Ivory Coast','Emmanuel Agbadou','DF'),
  ('Ivory Coast','Evan Ndicka','DF'),
  ('Ivory Coast','Evann Guessand','FW'),
  ('Ivory Coast','Alban Lafont','GK'),
  ('Ivory Coast','Bazoumana Touré','FW'),
  ('Ivory Coast','Parfait Guiagon','MF'),
  ('Ivory Coast','Christ Inao Oulaï','MF'),
  ('Japan','Zion Suzuki','GK'),
  ('Japan','Yukinari Sugawara','DF'),
  ('Japan','Shōgo Taniguchi','DF'),
  ('Japan','Kō Itakura','DF'),
  ('Japan','Yūto Nagatomo','DF'),
  ('Japan','Wataru Endo','MF'),
  ('Japan','Ao Tanaka','MF'),
  ('Japan','Takefusa Kubo','MF'),
  ('Japan','Keisuke Gotō','FW'),
  ('Japan','Ritsu Dōan','MF'),
  ('Japan','Daizen Maeda','MF'),
  ('Japan','Keisuke Ōsako','GK'),
  ('Japan','Keito Nakamura','MF'),
  ('Japan','Junya Itō','MF'),
  ('Japan','Daichi Kamada','MF'),
  ('Japan','Tsuyoshi Watanabe','DF'),
  ('Japan','Yuito Suzuki','MF'),
  ('Japan','Ayase Ueda','FW'),
  ('Japan','Kōki Ogawa','FW'),
  ('Japan','Ayumu Seko','DF'),
  ('Japan','Hiroki Itō','DF'),
  ('Japan','Takehiro Tomiyasu','DF'),
  ('Japan','Tomoki Hayakawa','GK'),
  ('Japan','Kaishū Sano','MF'),
  ('Japan','Junnosuke Suzuki','DF'),
  ('Japan','Kento Shiogai','FW'),
  ('Netherlands','Bart Verbruggen','GK'),
  ('Netherlands','Lutsharel Geertruida','DF'),
  ('Netherlands','Marten de Roon','MF'),
  ('Netherlands','Virgil van Dijk','DF'),
  ('Netherlands','Nathan Aké','DF'),
  ('Netherlands','Jan Paul van Hecke','DF'),
  ('Netherlands','Justin Kluivert','MF'),
  ('Netherlands','Ryan Gravenberch','MF'),
  ('Netherlands','Wout Weghorst','FW'),
  ('Netherlands','Memphis Depay','FW'),
  ('Netherlands','Cody Gakpo','FW'),
  ('Netherlands','Mats Wieffer','DF'),
  ('Netherlands','Robin Roefs','GK'),
  ('Netherlands','Tijjani Reijnders','MF'),
  ('Netherlands','Micky van de Ven','DF'),
  ('Netherlands','Guus Til','MF'),
  ('Netherlands','Noa Lang','FW'),
  ('Netherlands','Donyell Malen','FW'),
  ('Netherlands','Brian Brobbey','FW'),
  ('Netherlands','Teun Koopmeiners','MF'),
  ('Netherlands','Frenkie de Jong','MF'),
  ('Netherlands','Denzel Dumfries','DF'),
  ('Netherlands','Mark Flekken','GK'),
  ('Netherlands','Crysencio Summerville','FW'),
  ('Netherlands','Jorrel Hato','DF'),
  ('Netherlands','Quinten Timber','MF'),
  ('Sweden','Jacob Widell Zetterström','GK'),
  ('Sweden','Gustaf Lagerbielke','DF'),
  ('Sweden','Victor Lindelöf','DF'),
  ('Sweden','Isak Hien','DF'),
  ('Sweden','Gabriel Gudmundsson','DF'),
  ('Sweden','Herman Johansson','DF'),
  ('Sweden','Lucas Bergvall','MF'),
  ('Sweden','Daniel Svensson','DF'),
  ('Sweden','Alexander Isak','FW'),
  ('Sweden','Benjamin Nygren','MF'),
  ('Sweden','Anthony Elanga','FW'),
  ('Sweden','Viktor Johansson','GK'),
  ('Sweden','Ken Sema','MF'),
  ('Sweden','Hjalmar Ekdal','DF'),
  ('Sweden','Carl Starfelt','DF'),
  ('Sweden','Jesper Karlström','MF'),
  ('Sweden','Viktor Gyökeres','FW'),
  ('Sweden','Yasin Ayari','MF'),
  ('Sweden','Mattias Svanberg','MF'),
  ('Sweden','Eric Smith','DF'),
  ('Sweden','Alexander Bernhardsson','DF'),
  ('Sweden','Besfort Zeneli','MF'),
  ('Sweden','Kristoffer Nordfeldt','GK'),
  ('Sweden','Elliot Stroud','DF'),
  ('Sweden','Gustaf Nilsson','FW'),
  ('Sweden','Taha Ali','FW'),
  ('Tunisia','Mouhib Chamakh','GK'),
  ('Tunisia','Ali Abdi','DF'),
  ('Tunisia','Montassar Talbi','DF'),
  ('Tunisia','Omar Rekik','DF'),
  ('Tunisia','Adem Arous','DF'),
  ('Tunisia','Dylan Bronn','DF'),
  ('Tunisia','Elias Achouri','FW'),
  ('Tunisia','Elias Saad','FW'),
  ('Tunisia','Hazem Mastouri','FW'),
  ('Tunisia','Hannibal Mejbri','MF'),
  ('Tunisia','Ismaël Gharbi','MF'),
  ('Tunisia','Mortadha Ben Ouanes','DF'),
  ('Tunisia','Rani Khedira','MF'),
  ('Tunisia','Khalil Ayari','MF'),
  ('Tunisia','Hadj Mahmoud','MF'),
  ('Tunisia','Aymen Dahmen','GK'),
  ('Tunisia','Ellyes Skhiri','MF'),
  ('Tunisia','Rayan Elloumi','FW'),
  ('Tunisia','Firas Chaouat','FW'),
  ('Tunisia','Yan Valery','DF'),
  ('Tunisia','Mohamed Amine Ben Hamida','DF'),
  ('Tunisia','Sabri Ben Hessen','GK'),
  ('Tunisia','Moutaz Neffati','DF'),
  ('Tunisia','Raed Chikhaoui','DF'),
  ('Tunisia','Anis Ben Slimane','MF'),
  ('Tunisia','Sebastian Tounekti','MF'),
  ('Belgium','Thibaut Courtois','GK'),
  ('Belgium','Zeno Debast','DF'),
  ('Belgium','Arthur Theate','DF'),
  ('Belgium','Brandon Mechele','DF'),
  ('Belgium','Maxim De Cuyper','DF'),
  ('Belgium','Axel Witsel','MF'),
  ('Belgium','Kevin De Bruyne','MF'),
  ('Belgium','Youri Tielemans','MF'),
  ('Belgium','Romelu Lukaku','FW'),
  ('Belgium','Leandro Trossard','FW'),
  ('Belgium','Jérémy Doku','FW'),
  ('Belgium','Senne Lammens','GK'),
  ('Belgium','Mike Penders','GK'),
  ('Belgium','Dodi Lukébakio','FW'),
  ('Belgium','Thomas Meunier','DF'),
  ('Belgium','Koni De Winter','DF'),
  ('Belgium','Charles De Ketelaere','FW'),
  ('Belgium','Joaquin Seys','DF'),
  ('Belgium','Diego Moreira','MF'),
  ('Belgium','Hans Vanaken','MF'),
  ('Belgium','Timothy Castagne','DF'),
  ('Belgium','Alexis Saelemaekers','MF'),
  ('Belgium','Nicolas Raskin','MF'),
  ('Belgium','Amadou Onana','MF'),
  ('Belgium','Nathan Ngoy','DF'),
  ('Belgium','Matias Fernandez-Pardo','FW'),
  ('Egypt','Mohamed El Shenawy','GK'),
  ('Egypt','Yasser Ibrahim','DF'),
  ('Egypt','Mohamed Hany','DF'),
  ('Egypt','Hossam Abdelmaguid','DF'),
  ('Egypt','Ramy Rabia','DF'),
  ('Egypt','Mohamed Abdelmonem','DF'),
  ('Egypt','Trézéguet','FW'),
  ('Egypt','Emam Ashour','MF'),
  ('Egypt','Hamza Abdelkarim','FW'),
  ('Egypt','Mohamed Salah','FW'),
  ('Egypt','Mostafa Ziko','MF'),
  ('Egypt','Haissem Hassan','FW'),
  ('Egypt','Ahmed Fatouh','DF'),
  ('Egypt','Hamdy Fathy','MF'),
  ('Egypt','Karim Hafez','DF'),
  ('Egypt','El Mahdy Soliman','GK'),
  ('Egypt','Mohanad Lasheen','MF'),
  ('Egypt','Nabil Emad','MF'),
  ('Egypt','Marwan Attia','MF'),
  ('Egypt','Ibrahim Adel','FW'),
  ('Egypt','Mahmoud Saber','MF'),
  ('Egypt','Omar Marmoush','FW'),
  ('Egypt','Mostafa Shobeir','GK'),
  ('Egypt','Tarek Alaa','DF'),
  ('Egypt','Zizo','FW'),
  ('Egypt','Mohamed Alaa','GK'),
  ('Iran','Alireza Beiranvand','GK'),
  ('Iran','Saleh Hardani','DF'),
  ('Iran','Ehsan Hajsafi','DF'),
  ('Iran','Shojae Khalilzadeh','DF'),
  ('Iran','Milad Mohammadi','DF'),
  ('Iran','Saeid Ezatolahi','MF'),
  ('Iran','Alireza Jahanbakhsh','MF'),
  ('Iran','Mohammad Mohebi','MF'),
  ('Iran','Mehdi Taremi','FW'),
  ('Iran','Mehdi Ghayedi','FW'),
  ('Iran','Ali Alipour','FW'),
  ('Iran','Payam Niazmand','GK'),
  ('Iran','Hossein Kanaanizadegan','DF'),
  ('Iran','Saman Ghoddos','MF'),
  ('Iran','Rouzbeh Cheshmi','MF'),
  ('Iran','Mehdi Torabi','MF'),
  ('Iran','Aria Yousefi','DF'),
  ('Iran','Amirhossein Hosseinzadeh','FW'),
  ('Iran','Ali Nemati','DF'),
  ('Iran','Shahriyar Moghanlou','FW'),
  ('Iran','Mohammad Ghorbani','MF'),
  ('Iran','Hossein Hosseini','GK'),
  ('Iran','Ramin Rezaeian','DF'),
  ('Iran','Dennis Eckert','FW'),
  ('Iran','Danial Eiri','DF'),
  ('Iran','Amirmohammad Razzaghinia','MF'),
  ('New Zealand','Max Crocombe','GK'),
  ('New Zealand','Tim Payne','DF'),
  ('New Zealand','Francis de Vries','DF'),
  ('New Zealand','Tyler Bindon','DF'),
  ('New Zealand','Michael Boxall','DF'),
  ('New Zealand','Joe Bell','MF'),
  ('New Zealand','Matthew Garbett','MF'),
  ('New Zealand','Marko Stamenić','MF'),
  ('New Zealand','Chris Wood','FW'),
  ('New Zealand','Sarpreet Singh','MF'),
  ('New Zealand','Elijah Just','MF'),
  ('New Zealand','Alex Paulsen','GK'),
  ('New Zealand','Liberato Cacace','DF'),
  ('New Zealand','Alex Rufer','MF'),
  ('New Zealand','Nando Pijnaker','DF'),
  ('New Zealand','Finn Surman','DF'),
  ('New Zealand','Kosta Barbarouses','FW'),
  ('New Zealand','Ben Waine','FW'),
  ('New Zealand','Ben Old','MF'),
  ('New Zealand','Callum McCowatt','MF'),
  ('New Zealand','Jesse Randall','FW'),
  ('New Zealand','Michael Woud','GK'),
  ('New Zealand','Ryan Thomas','MF'),
  ('New Zealand','Callan Elliot','DF'),
  ('New Zealand','Lachlan Bayliss','MF'),
  ('New Zealand','Tommy Smith','DF'),
  ('Cape Verde','Vozinha','GK'),
  ('Cape Verde','Stopira','DF'),
  ('Cape Verde','Diney','DF'),
  ('Cape Verde','Roberto Lopes','DF'),
  ('Cape Verde','Logan Costa','DF'),
  ('Cape Verde','Kevin Pina','MF'),
  ('Cape Verde','Jovane Cabral','MF'),
  ('Cape Verde','João Paulo','MF'),
  ('Cape Verde','Gilson Benchimol','FW'),
  ('Cape Verde','Jamiro Monteiro','MF'),
  ('Cape Verde','Garry Rodrigues','MF'),
  ('Cape Verde','Márcio Rosa','GK'),
  ('Cape Verde','Sidny Lopes Cabral','DF'),
  ('Cape Verde','Deroy Duarte','MF'),
  ('Cape Verde','Laros Duarte','MF'),
  ('Cape Verde','Yannick Semedo','MF'),
  ('Cape Verde','Willy Semedo','MF'),
  ('Cape Verde','Telmo Arcanjo','MF'),
  ('Cape Verde','Dailon Livramento','FW'),
  ('Cape Verde','Ryan Mendes','FW'),
  ('Cape Verde','Nuno da Costa','MF'),
  ('Cape Verde','Steven Moreira','DF'),
  ('Cape Verde','CJ dos Santos','GK'),
  ('Cape Verde','Wagner Pina','DF'),
  ('Cape Verde','Kelvin Pires','DF'),
  ('Cape Verde','Hélio Varela','MF'),
  ('Saudi Arabia','Nawaf Al-Aqidi','GK'),
  ('Saudi Arabia','Ali Majrashi','DF'),
  ('Saudi Arabia','Ali Lajami','DF'),
  ('Saudi Arabia','Abdulelah Al-Amri','DF'),
  ('Saudi Arabia','Hassan Al-Tambakti','DF'),
  ('Saudi Arabia','Nasser Al-Dawsari','MF'),
  ('Saudi Arabia','Musab Al-Juwayr','MF'),
  ('Saudi Arabia','Ayman Yahya','FW'),
  ('Saudi Arabia','Firas Al-Buraikan','FW'),
  ('Saudi Arabia','Salem Al-Dawsari','FW'),
  ('Saudi Arabia','Saleh Al-Shehri','FW'),
  ('Saudi Arabia','Saud Abdulhamid','DF'),
  ('Saudi Arabia','Nawaf Boushal','DF'),
  ('Saudi Arabia','Hassan Kadesh','DF'),
  ('Saudi Arabia','Abdullah Al-Khaibari','MF'),
  ('Saudi Arabia','Ziyad Al-Johani','MF'),
  ('Saudi Arabia','Khalid Al-Ghannam','FW'),
  ('Saudi Arabia','Alaa Al-Hejji','MF'),
  ('Saudi Arabia','Abdullah Al-Hamdan','FW'),
  ('Saudi Arabia','Sultan Mandash','FW'),
  ('Saudi Arabia','Mohammed Al-Owais','GK'),
  ('Saudi Arabia','Ahmed Al-Kassar','GK'),
  ('Saudi Arabia','Mohamed Kanno','MF'),
  ('Saudi Arabia','Moteb Al-Harbi','DF'),
  ('Saudi Arabia','Jehad Thakri','DF'),
  ('Saudi Arabia','Mohammed Abu Al-Shamat','DF'),
  ('Spain','David Raya','GK'),
  ('Spain','Marc Pubill','DF'),
  ('Spain','Álex Grimaldo','DF'),
  ('Spain','Eric García','DF'),
  ('Spain','Marcos Llorente','DF'),
  ('Spain','Mikel Merino','MF'),
  ('Spain','Ferran Torres','FW'),
  ('Spain','Fabián Ruiz','MF'),
  ('Spain','Gavi','MF'),
  ('Spain','Dani Olmo','FW'),
  ('Spain','Yéremy Pino','FW'),
  ('Spain','Pedro Porro','DF'),
  ('Spain','Joan Garcia','GK'),
  ('Spain','Aymeric Laporte','DF'),
  ('Spain','Álex Baena','MF'),
  ('Spain','Rodri','MF'),
  ('Spain','Nico Williams','FW'),
  ('Spain','Martín Zubimendi','MF'),
  ('Spain','Lamine Yamal','FW'),
  ('Spain','Pedri','MF'),
  ('Spain','Mikel Oyarzabal','FW'),
  ('Spain','Pau Cubarsí','DF'),
  ('Spain','Unai Simón','GK'),
  ('Spain','Marc Cucurella','DF'),
  ('Spain','Víctor Muñoz','FW'),
  ('Spain','Borja Iglesias','FW'),
  ('Uruguay','Sergio Rochet','GK'),
  ('Uruguay','José Giménez','DF'),
  ('Uruguay','Sebastián Cáceres','DF'),
  ('Uruguay','Ronald Araújo','DF'),
  ('Uruguay','Manuel Ugarte','MF'),
  ('Uruguay','Rodrigo Bentancur','MF'),
  ('Uruguay','Nicolás de la Cruz','MF'),
  ('Uruguay','Federico Valverde','MF'),
  ('Uruguay','Darwin Núñez','FW'),
  ('Uruguay','Giorgian de Arrascaeta','MF'),
  ('Uruguay','Facundo Pellistri','FW'),
  ('Uruguay','Santiago Mele','GK'),
  ('Uruguay','Guillermo Varela','DF'),
  ('Uruguay','Agustín Canobbio','MF'),
  ('Uruguay','Emiliano Martínez','MF'),
  ('Uruguay','Mathías Olivera','DF'),
  ('Uruguay','Matías Viña','DF'),
  ('Uruguay','Brian Rodríguez','FW'),
  ('Uruguay','Rodrigo Aguirre','FW'),
  ('Uruguay','Maximiliano Araújo','MF'),
  ('Uruguay','Federico Viñas','FW'),
  ('Uruguay','Joaquín Piquerez','MF'),
  ('Uruguay','Fernando Muslera','GK'),
  ('Uruguay','Santiago Bueno','DF'),
  ('Uruguay','Juan Manuel Sanabria','MF'),
  ('Uruguay','Rodrigo Zalazar','MF'),
  ('France','Brice Samba','GK'),
  ('France','Malo Gusto','DF'),
  ('France','Lucas Digne','DF'),
  ('France','Dayot Upamecano','DF'),
  ('France','Jules Koundé','DF'),
  ('France','Manu Koné','MF'),
  ('France','Ousmane Dembélé','FW'),
  ('France','Aurélien Tchouaméni','MF'),
  ('France','Marcus Thuram','FW'),
  ('France','Kylian Mbappé','FW'),
  ('France','Michael Olise','FW'),
  ('France','Bradley Barcola','FW'),
  ('France','N''Golo Kanté','MF'),
  ('France','Adrien Rabiot','MF'),
  ('France','Ibrahima Konaté','DF'),
  ('France','Mike Maignan','GK'),
  ('France','William Saliba','DF'),
  ('France','Warren Zaïre-Emery','MF'),
  ('France','Théo Hernandez','DF'),
  ('France','Désiré Doué','FW'),
  ('France','Lucas Hernandez','DF'),
  ('France','Jean-Philippe Mateta','FW'),
  ('France','Robin Risser','GK'),
  ('France','Rayan Cherki','MF'),
  ('France','Maghnes Akliouche','MF'),
  ('France','Maxence Lacroix','DF'),
  ('Iraq','Fahad Talib','GK'),
  ('Iraq','Rebin Sulaka','DF'),
  ('Iraq','Hussein Ali','DF'),
  ('Iraq','Zaid Tahseen','DF'),
  ('Iraq','Akam Hashim','DF'),
  ('Iraq','Manaf Younis','DF'),
  ('Iraq','Youssef Amyn','MF'),
  ('Iraq','Ibrahim Bayesh','MF'),
  ('Iraq','Ali Al-Hamadi','FW'),
  ('Iraq','Mohanad Ali','FW'),
  ('Iraq','Ahmed Qasem','FW'),
  ('Iraq','Jalal Hassan','GK'),
  ('Iraq','Ali Yousif','FW'),
  ('Iraq','Zidane Iqbal','MF'),
  ('Iraq','Ahmed Maknzi','DF'),
  ('Iraq','Amir Al-Ammari','MF'),
  ('Iraq','Ali Jasim','FW'),
  ('Iraq','Aymen Hussein','FW'),
  ('Iraq','Kevin Yakob','MF'),
  ('Iraq','Aimar Sher','MF'),
  ('Iraq','Marko Farji','FW'),
  ('Iraq','Ahmed Basil','GK'),
  ('Iraq','Merchas Doski','DF'),
  ('Iraq','Zaid Ismail','MF'),
  ('Iraq','Mustafa Saadoon','DF'),
  ('Iraq','Frans Putros','DF'),
  ('Norway','Ørjan Nyland','GK'),
  ('Norway','Morten Thorsby','MF'),
  ('Norway','Kristoffer Ajer','DF'),
  ('Norway','Leo Østigård','DF'),
  ('Norway','David Møller Wolfe','DF'),
  ('Norway','Patrick Berg','MF'),
  ('Norway','Alexander Sørloth','FW'),
  ('Norway','Sander Berge','MF'),
  ('Norway','Erling Haaland','FW'),
  ('Norway','Martin Ødegaard','MF'),
  ('Norway','Jørgen Strand Larsen','FW'),
  ('Norway','Sander Tangvik','GK'),
  ('Norway','Egil Selvik','GK'),
  ('Norway','Fredrik Aursnes','MF'),
  ('Norway','Fredrik André Bjørkan','DF'),
  ('Norway','Marcus Holmgren Pedersen','DF'),
  ('Norway','Torbjørn Heggem','DF'),
  ('Norway','Kristian Thorstvedt','MF'),
  ('Norway','Thelo Aasgaard','MF'),
  ('Norway','Antonio Nusa','FW'),
  ('Norway','Andreas Schjelderup','MF'),
  ('Norway','Oscar Bobb','MF'),
  ('Norway','Jens Petter Hauge','MF'),
  ('Norway','Sondre Langås','DF'),
  ('Norway','Henrik Falchener','DF'),
  ('Norway','Julian Ryerson','FW'),
  ('Senegal','Yehvann Diouf','GK'),
  ('Senegal','Mamadou Sarr','DF'),
  ('Senegal','Kalidou Koulibaly','DF'),
  ('Senegal','Abdoulaye Seck','DF'),
  ('Senegal','Idrissa Gueye','MF'),
  ('Senegal','Pathé Ciss','MF'),
  ('Senegal','Assane Diao','FW'),
  ('Senegal','Lamine Camara','MF'),
  ('Senegal','Bamba Dieng','FW'),
  ('Senegal','Sadio Mané','FW'),
  ('Senegal','Nicolas Jackson','FW'),
  ('Senegal','Cherif Ndiaye','FW'),
  ('Senegal','Iliman Ndiaye','FW'),
  ('Senegal','Ismail Jakobs','DF'),
  ('Senegal','Krépin Diatta','DF'),
  ('Senegal','Édouard Mendy','GK'),
  ('Senegal','Pape Matar Sarr','MF'),
  ('Senegal','Ismaïla Sarr','FW'),
  ('Senegal','Moussa Niakhaté','DF'),
  ('Senegal','Ibrahim Mbaye','FW'),
  ('Senegal','Habib Diarra','MF'),
  ('Senegal','Bara Sapoko Ndiaye','MF'),
  ('Senegal','Mory Diaw','GK'),
  ('Senegal','Antoine Mendy','DF'),
  ('Senegal','El Hadji Malick Diouf','DF'),
  ('Senegal','Pape Gueye','MF'),
  ('Algeria','Melvin Mastil','GK'),
  ('Algeria','Aïssa Mandi','DF'),
  ('Algeria','Achref Abada','DF'),
  ('Algeria','Mohamed Amine Tougai','DF'),
  ('Algeria','Zineddine Belaïd','DF'),
  ('Algeria','Ramiz Zerrouki','MF'),
  ('Algeria','Riyad Mahrez','FW'),
  ('Algeria','Houssem Aouar','MF'),
  ('Algeria','Amine Gouiri','FW'),
  ('Algeria','Farès Chaïbi','MF'),
  ('Algeria','Anis Hadj Moussa','FW'),
  ('Algeria','Nadhir Benbouali','FW'),
  ('Algeria','Jaouen Hadjam','DF'),
  ('Algeria','Hicham Boudaoui','MF'),
  ('Algeria','Rayan Aït-Nouri','DF'),
  ('Algeria','Oussama Benbot','GK'),
  ('Algeria','Rafik Belghali','DF'),
  ('Algeria','Mohamed Amoura','FW'),
  ('Algeria','Nabil Bentaleb','MF'),
  ('Algeria','Adil Boulbina','FW'),
  ('Algeria','Ramy Bensebaini','DF'),
  ('Algeria','Ibrahim Maza','MF'),
  ('Algeria','Luca Zidane','GK'),
  ('Algeria','Yacine Titraoui','MF'),
  ('Algeria','Farès Ghedjemis','FW'),
  ('Algeria','Samir Chergui','DF'),
  ('Argentina','Juan Musso','GK'),
  ('Argentina','Marcos Nicolás Senesi Baron','MF'),
  ('Argentina','Nicolás Tagliafico','DF'),
  ('Argentina','Gonzalo Montiel','DF'),
  ('Argentina','Leandro Paredes','MF'),
  ('Argentina','Lisandro Martínez','DF'),
  ('Argentina','Rodrigo De Paul','MF'),
  ('Argentina','Valentín Barco','MF'),
  ('Argentina','Julián Alvarez','FW'),
  ('Argentina','Lionel Messi','FW'),
  ('Argentina','Giovani Lo Celso','MF'),
  ('Argentina','Gerónimo Rulli','GK'),
  ('Argentina','Cristian Romero','DF'),
  ('Argentina','Exequiel Palacios','MF'),
  ('Argentina','Nicolás González','MF'),
  ('Argentina','Thiago Almada','FW'),
  ('Argentina','Giuliano Simeone','FW'),
  ('Argentina','Nico Paz','FW'),
  ('Argentina','Nicolás Otamendi','DF'),
  ('Argentina','Alexis Mac Allister','MF'),
  ('Argentina','José Manuel López','FW'),
  ('Argentina','Lautaro Martínez','FW'),
  ('Argentina','Emiliano Martínez','GK'),
  ('Argentina','Enzo Fernández','MF'),
  ('Argentina','Facundo Medina','DF'),
  ('Argentina','Nahuel Molina','DF'),
  ('Austria','Alexander Schlager','GK'),
  ('Austria','David Affengruber','DF'),
  ('Austria','Kevin Danso','DF'),
  ('Austria','Xaver Schlager','MF'),
  ('Austria','Stefan Posch','DF'),
  ('Austria','Nicolas Seiwald','MF'),
  ('Austria','Marko Arnautović','FW'),
  ('Austria','David Alaba','DF'),
  ('Austria','Marcel Sabitzer','MF'),
  ('Austria','Florian Grillitsch','MF'),
  ('Austria','Michael Gregoritsch','FW'),
  ('Austria','Florian Wiegele','GK'),
  ('Austria','Patrick Pentz','GK'),
  ('Austria','Saša Kalajdžić','FW'),
  ('Austria','Philipp Lienhart','DF'),
  ('Austria','Phillipp Mwene','DF'),
  ('Austria','Carney Chukwuemeka','MF'),
  ('Austria','Romano Schmid','MF'),
  ('Austria','Dejan Ljubičić','MF'),
  ('Austria','Konrad Laimer','MF'),
  ('Austria','Patrick Wimmer','FW'),
  ('Austria','Alexander Prass','MF'),
  ('Austria','Marco Friedl','DF'),
  ('Austria','Paul Wanner','MF'),
  ('Austria','Michael Svoboda','DF'),
  ('Austria','Alessandro Schöpf','MF'),
  ('Jordan','Yazeed Abulaila','GK'),
  ('Jordan','Mohammad Abu Hashish','DF'),
  ('Jordan','Abdallah Nasib','DF'),
  ('Jordan','Husam Abu Dahab','DF'),
  ('Jordan','Yazan Al-Arab','DF'),
  ('Jordan','Amer Jamous','MF'),
  ('Jordan','Mohammad Abu Zrayq','FW'),
  ('Jordan','Noor Al-Rawabdeh','MF'),
  ('Jordan','Ali Olwan','FW'),
  ('Jordan','Musa Al-Taamari','FW'),
  ('Jordan','Odeh Al-Fakhouri','FW'),
  ('Jordan','Nour Bani Attiah','GK'),
  ('Jordan','Mahmoud Al-Mardi','FW'),
  ('Jordan','Rajaei Ayed','MF'),
  ('Jordan','Ibrahim Sadeh','MF'),
  ('Jordan','Mo Abualnadi','DF'),
  ('Jordan','Salim Obaid','DF'),
  ('Jordan','Mohammad Ahmed Mohammad Taha','MF'),
  ('Jordan','Saed Al-Rosan','DF'),
  ('Jordan','Mohannad Abu Taha','MF'),
  ('Jordan','Nizar Al-Rashdan','MF'),
  ('Jordan','Abdallah Al-Fakhouri','GK'),
  ('Jordan','Ihsan Haddad','DF'),
  ('Jordan','Ali Azaizeh','FW'),
  ('Jordan','Mohammad Al-Dawoud','MF'),
  ('Jordan','Anas Badawi','DF'),
  ('Colombia','David Ospina','GK'),
  ('Colombia','Daniel Muñoz','DF'),
  ('Colombia','Jhon Lucumí','DF'),
  ('Colombia','Santiago Arias','DF'),
  ('Colombia','Kevin Castaño','MF'),
  ('Colombia','Richard Ríos','MF'),
  ('Colombia','Luis Díaz','FW'),
  ('Colombia','Jorge Carrascal','MF'),
  ('Colombia','Jhon Córdoba','FW'),
  ('Colombia','James Rodríguez','MF'),
  ('Colombia','Jhon Arias','MF'),
  ('Colombia','Camilo Vargas','GK'),
  ('Colombia','Yerry Mina','DF'),
  ('Colombia','Gustavo Puerta','DF'),
  ('Colombia','Juan Portilla','MF'),
  ('Colombia','Jefferson Lerma','MF'),
  ('Colombia','Johan Mojica','DF'),
  ('Colombia','Willer Ditta','DF'),
  ('Colombia','Cucho Hernández','FW'),
  ('Colombia','Juan Fernando Quintero','MF'),
  ('Colombia','Jaminton Campaz','FW'),
  ('Colombia','Deiver Machado','DF'),
  ('Colombia','Davinson Sánchez','DF'),
  ('Colombia','Álvaro Montero','GK'),
  ('Colombia','Luis Suárez','FW'),
  ('Colombia','Andrés Gómez','FW'),
  ('DR Congo','Lionel Mpasi','GK'),
  ('DR Congo','Aaron Wan-Bissaka','DF'),
  ('DR Congo','Steve Kapuadi','DF'),
  ('DR Congo','Axel Tuanzebe','DF'),
  ('DR Congo','Dylan Batubinsika','DF'),
  ('DR Congo','Ngal''ayel Mukau','MF'),
  ('DR Congo','Nathanaël Mbuku','MF'),
  ('DR Congo','Samuel Moutoussamy','MF'),
  ('DR Congo','Brian Cipenga','FW'),
  ('DR Congo','Théo Bongonda','MF'),
  ('DR Congo','Gaël Kakuta','FW'),
  ('DR Congo','Joris Kayembe','DF'),
  ('DR Congo','Meschak Elia','FW'),
  ('DR Congo','Noah Sadiki','MF'),
  ('DR Congo','Aaron Tshibola','MF'),
  ('DR Congo','Timothy Fayulu','GK'),
  ('DR Congo','Cédric Bakambu','FW'),
  ('DR Congo','Charles Pickel','MF'),
  ('DR Congo','Fiston Mayele','FW'),
  ('DR Congo','Yoane Wissa','FW'),
  ('DR Congo','Matthieu Epolo','GK'),
  ('DR Congo','Chancel Mbemba','DF'),
  ('DR Congo','Simon Banza','FW'),
  ('DR Congo','Gédéon Kalulu','DF'),
  ('DR Congo','Edo Kayembe','MF'),
  ('DR Congo','Arthur Masuaku','DF'),
  ('Portugal','Diogo Costa','GK'),
  ('Portugal','Nélson Semedo','DF'),
  ('Portugal','Rúben Dias','DF'),
  ('Portugal','Tomás Araújo','DF'),
  ('Portugal','Diogo Dalot','DF'),
  ('Portugal','Matheus Nunes','MF'),
  ('Portugal','Cristiano Ronaldo','FW'),
  ('Portugal','Bruno Fernandes','MF'),
  ('Portugal','Gonçalo Ramos','FW'),
  ('Portugal','Bernardo Silva','MF'),
  ('Portugal','João Félix','FW'),
  ('Portugal','José Sá','GK'),
  ('Portugal','Renato Veiga','DF'),
  ('Portugal','Gonçalo Inácio','DF'),
  ('Portugal','João Neves','MF'),
  ('Portugal','Francisco Trincão','FW'),
  ('Portugal','Rafael Leão','FW'),
  ('Portugal','Pedro Neto','FW'),
  ('Portugal','Gonçalo Guedes','FW'),
  ('Portugal','João Cancelo','DF'),
  ('Portugal','Rúben Neves','MF'),
  ('Portugal','Rui Silva','GK'),
  ('Portugal','Vitinha','MF'),
  ('Portugal','Samú Costa','DF'),
  ('Portugal','Nuno Mendes','DF'),
  ('Portugal','Francisco Conceição','FW'),
  ('Uzbekistan','Utkir Yusupov','GK'),
  ('Uzbekistan','Abdukodir Khusanov','DF'),
  ('Uzbekistan','Khojiakbar Alijonov','DF'),
  ('Uzbekistan','Farrukh Sayfiev','DF'),
  ('Uzbekistan','Rustam Ashurmatov','DF'),
  ('Uzbekistan','Akmal Mozgovoy','MF'),
  ('Uzbekistan','Otabek Shukurov','MF'),
  ('Uzbekistan','Jamshid Iskanderov','MF'),
  ('Uzbekistan','Odiljon Hamrobekov','MF'),
  ('Uzbekistan','Jaloliddin Masharipov','MF'),
  ('Uzbekistan','Oston Urunov','MF'),
  ('Uzbekistan','Abduvohid Nematov','GK'),
  ('Uzbekistan','Sherzod Nasrullaev','DF'),
  ('Uzbekistan','Eldor Shomurodov','FW'),
  ('Uzbekistan','Umar Eshmurodov','DF'),
  ('Uzbekistan','Botirali Ergashev','GK'),
  ('Uzbekistan','Dostonbek Khamdamov','MF'),
  ('Uzbekistan','Abdulla Abdullaev','DF'),
  ('Uzbekistan','Azizjon Ganiev','MF'),
  ('Uzbekistan','Azizbek Amonov','FW'),
  ('Uzbekistan','Igor Sergeev','FW'),
  ('Uzbekistan','Abbosbek Fayzullaev','MF'),
  ('Uzbekistan','Sherzod Esanov','MF'),
  ('Uzbekistan','Bekhruz Karimov','DF'),
  ('Uzbekistan','Avazbek Ulmasaliev','DF'),
  ('Uzbekistan','Jakhongir Urozov','DF'),
  ('Croatia','Dominik Livaković','GK'),
  ('Croatia','Josip Stanišić','DF'),
  ('Croatia','Marin Pongračić','DF'),
  ('Croatia','Joško Gvardiol','DF'),
  ('Croatia','Duje Ćaleta-Car','DF'),
  ('Croatia','Josip Šutalo','DF'),
  ('Croatia','Nikola Moro','MF'),
  ('Croatia','Mateo Kovačić','MF'),
  ('Croatia','Andrej Kramarić','FW'),
  ('Croatia','Luka Modrić','MF'),
  ('Croatia','Ante Budimir','FW'),
  ('Croatia','Ivor Pandur','GK'),
  ('Croatia','Nikola Vlašić','MF'),
  ('Croatia','Ivan Perišić','FW'),
  ('Croatia','Mario Pašalić','MF'),
  ('Croatia','Martin Baturina','MF'),
  ('Croatia','Petar Sučić','MF'),
  ('Croatia','Kristijan Jakić','DF'),
  ('Croatia','Toni Fruk','MF'),
  ('Croatia','Igor Matanović','FW'),
  ('Croatia','Luka Sučić','MF'),
  ('Croatia','Luka Vušković','DF'),
  ('Croatia','Dominik Kotarski','GK'),
  ('Croatia','Marco Pašalić','FW'),
  ('Croatia','Martin Erlić','DF'),
  ('Croatia','Petar Musa','FW'),
  ('England','Jordan Pickford','GK'),
  ('England','Ezri Konsa','DF'),
  ('England','Nico O''Reilly','DF'),
  ('England','Declan Rice','MF'),
  ('England','John Stones','DF'),
  ('England','Marc Guéhi','DF'),
  ('England','Bukayo Saka','FW'),
  ('England','Elliot Anderson','MF'),
  ('England','Harry Kane','FW'),
  ('England','Jude Bellingham','MF'),
  ('England','Marcus Rashford','FW'),
  ('England','Tino Livramento','DF'),
  ('England','Dean Henderson','GK'),
  ('England','Jordan Henderson','MF'),
  ('England','Dan Burn','DF'),
  ('England','Kobbie Mainoo','MF'),
  ('England','Morgan Rogers','MF'),
  ('England','Anthony Gordon','FW'),
  ('England','Ollie Watkins','FW'),
  ('England','Noni Madueke','FW'),
  ('England','Eberechi Eze','MF'),
  ('England','Ivan Toney','FW'),
  ('England','James Trafford','GK'),
  ('England','Reece James','DF'),
  ('England','Djed Spence','DF'),
  ('England','Jarell Quansah','DF'),
  ('Ghana','Lawrence Ati-Zigi','GK'),
  ('Ghana','Alidu Seidu','DF'),
  ('Ghana','Caleb Yirenkyi','MF'),
  ('Ghana','Jonas Adjetey','DF'),
  ('Ghana','Thomas Partey','MF'),
  ('Ghana','Abdul Mumin','DF'),
  ('Ghana','Abdul Fatawu','FW'),
  ('Ghana','Kwasi Sibo','MF'),
  ('Ghana','Jordan Ayew','FW'),
  ('Ghana','Brandon Thomas-Asante','FW'),
  ('Ghana','Antoine Semenyo','MF'),
  ('Ghana','Joseph Anang','GK'),
  ('Ghana','Christopher Bonsu Baah','FW'),
  ('Ghana','Gideon Mensah','DF'),
  ('Ghana','Elisha Owusu','MF'),
  ('Ghana','Benjamin Asare','GK'),
  ('Ghana','Abdul Rahman Baba','DF'),
  ('Ghana','Jerome Opoku','DF'),
  ('Ghana','Iñaki Williams','FW'),
  ('Ghana','Augustine Boakye','MF'),
  ('Ghana','Kojo Peprah Oppong','DF'),
  ('Ghana','Kamaldeen Sulemana','FW'),
  ('Ghana','Derrick Luckassen','DF'),
  ('Ghana','Ernest Nuamah','FW'),
  ('Ghana','Prince Kwabena Adu','FW'),
  ('Ghana','Marvin Senaya','DF'),
  ('Panama','Luis Mejía','GK'),
  ('Panama','César Blackman','DF'),
  ('Panama','José Córdoba','DF'),
  ('Panama','Fidel Escobar','DF'),
  ('Panama','Edgardo Fariña','DF'),
  ('Panama','Cristian Martínez','MF'),
  ('Panama','José Luis Rodríguez','MF'),
  ('Panama','Adalberto Carrasquilla','MF'),
  ('Panama','Tomás Rodríguez','FW'),
  ('Panama','Ismael Díaz','MF'),
  ('Panama','Yoel Bárcenas','MF'),
  ('Panama','César Samudio','GK'),
  ('Panama','Jiovany Ramos','DF'),
  ('Panama','Carlos Harvey','DF'),
  ('Panama','Eric Davis','DF'),
  ('Panama','Andrés Andrade','DF'),
  ('Panama','José Fajardo','FW'),
  ('Panama','Cecilio Waterman','FW'),
  ('Panama','Alberto Quintero','MF'),
  ('Panama','Aníbal Godoy','MF'),
  ('Panama','César Yanis','MF'),
  ('Panama','Orlando Mosquera','GK'),
  ('Panama','Michael Amir Murillo','DF'),
  ('Panama','Azarias Londoño','FW'),
  ('Panama','Roderick Miller','DF'),
  ('Panama','Jorge Gutiérrez','DF')
on conflict (team, player) do nothing;
